name: Generate contribution snake

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure assets directory
        run: mkdir -p assets

      - name: Generate snake SVG
        uses: Platane/snk@main
        with:
          github_user_name: eqwgeryfgbdf
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark
            assets/snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit snake
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/
            git commit -m "chore: update contribution snake [skip ci]"
            git push
          fi


